### ISSUE TITLE
Watcher listen to subdirectory?

### ISSUE THREAD

**Issue by TommyZhang-z** [yyjlincoln-unsw/lts#1]
Hi Lincoln, I am trying to set up similar directory structure like using react.(where you will have a src folder and package.json on the root folder). I found out that lts does not work if the files in the subdirectory has changed. 
![image](https://user-images.githubusercontent.com/81734746/176091216-c1d3aa95-8f7d-4a25-bbc6-62844b310f1c.png)

So I was hoping to have lts listen all files from subdirectory? Or specify a path to listen? Cuz i just need it to listen to my src folder, but didn't want to move the script in.

Cheers,

Tommy Zhang

**Comment by yyjlincoln** [comment]
Hi Tommy,
I'm currently looking into this feature - and I hope that I can finish it by next week. I will keep you updated.
You can also contribute to the project in the `dev` branch.

**Comment by yyjlincoln** [comment]
Version 1.5.0 has been released. This feature is now possible with the `change-all` flag. Please find that release in Github releases.

I'm not sure how this might impact the performance but I think it should be manageable.

You can run `lts update` periodically to check for the latest version (and the release links), if you're using LTS v1.4.0 or above. Alternatively you can also come to Github to check for it.
